<?php
// Language translations array
$translations = [
    'ar' => [
        // General
        'dashboard' => 'لوحة التحكم',
        'orders' => 'الطلبات',
        'companies' => 'الشركات',
        'drivers' => 'السائقين',
        'complaints' => 'الشكاوى',
        'feedback' => 'ملاحظات العملاء',
        'reports' => 'التقارير',
        'revenue' => 'الإيرادات',
        'driver_earnings' => 'التحصيل من السواق',
        'employees' => 'الموظفين',
        'profile' => 'الملف الشخصي',
        'logout' => 'تسجيل الخروج',
        'notifications' => 'الإشعارات',
        'admin_panel' => 'لوحة تحكم المشرف',
        
        // Status
        'status_active' => 'نشط',
        'status_inactive' => 'معطل',
        'status_pending' => 'قيد الانتظار',
        'status_accepted' => 'تم القبول',
        'status_in_transit' => 'جاري التوصيل',
        'status_delivered' => 'تم التوصيل',
        'status_cancelled' => 'ملغي',
        'status_unknown' => 'غير معروف',
        
        // Driver Status
        'driver_available' => 'متاح',
        'driver_busy' => 'مشغول',
        'driver_offline' => 'غير متصل',
        
        // Actions
        'whatsapp' => 'تواصل عبر واتساب',
        'edit' => 'تعديل',
        'delete' => 'حذف',
        'activate' => 'تفعيل',
        'deactivate' => 'تعطيل',
        'save' => 'حفظ',
        'cancel' => 'إلغاء',
        'search' => 'بحث',
        'add_new' => 'إضافة جديد',
        'view' => 'عرض',
        'export' => 'تصدير',
        'print' => 'طباعة',
        
        // System
        'system_title' => 'نظام إدارة النقل',
        'loading' => 'جاري التحميل...',
        'no_data' => 'لا توجد بيانات',
        'error' => 'خطأ',
        'success' => 'نجاح',
        'warning' => 'تحذير',
        'info' => 'معلومات',
        
        'orders_management' => 'إدارة الطلبات',
        'companies_management' => 'إدارة الشركات',
        'drivers_management' => 'إدارة السائقين',
        'complaints_management' => 'إدارة الشكاوى',
        'feedback_management' => 'إدارة الملاحظات',
        'reports_management' => 'إدارة التقارير',
        'revenue_management' => 'إدارة الإيرادات',
        'driver_earnings_management' => 'إدارة التحصيل من السواق',
        'employees_management' => 'إدارة الموظفين',
        
        // Companies
        'company_name' => 'اسم الشركة',
        'company_email' => 'البريد الإلكتروني',
        'company_phone' => 'رقم الهاتف',
        'company_address' => 'العنوان',
        'company_logo' => 'شعار الشركة',
        'company_contact' => 'الشخص المسؤول',
        'total_orders' => 'عدد الطلبات',
        'registration_date' => 'تاريخ التسجيل',
        
        // Confirmations
        'confirm_delete' => 'هل أنت متأكد من حذف هذا العنصر؟',
        'confirm_activate' => 'هل أنت متأكد من تفعيل هذا العنصر؟',
        'confirm_deactivate' => 'هل أنت متأكد من تعطيل هذا العنصر؟',
        
        // Navigation
        'previous' => 'السابق',
        'next' => 'التالي',
        'page_navigation' => 'التنقل بين الصفحات',
        
        // Messages
        'no_results' => 'لا توجد نتائج',
        'success_message' => 'تمت العملية بنجاح',
        'error_message' => 'حدث خطأ',
        'required_field' => 'هذا الحقل مطلوب',
        
        // Common
        'date' => 'التاريخ',
        'time' => 'الوقت',
        'status' => 'الحالة',
        'actions' => 'الإجراءات',
        'details' => 'التفاصيل',
        'notes' => 'ملاحظات',
        'description' => 'الوصف',
        'type' => 'النوع',
        'category' => 'الفئة',
        'price' => 'السعر',
        'quantity' => 'الكمية',
        'total' => 'المجموع',
        
        // Company Form
        'edit_company' => 'تعديل شركة',
        'add_company' => 'إضافة شركة',
        'add_new_company' => 'إضافة شركة جديدة',
        'upload_company_logo' => 'تحميل شعار الشركة',
        'commercial_record' => 'السجل التجاري',
        'tax_number' => 'الرقم الضريبي',
        'contact_person' => 'الشخص المسؤول',
        'contact_phone' => 'هاتف المسؤول',
        'activate_company' => 'تفعيل الشركة',
        
        // Form Validation
        'invalid_email' => 'البريد الإلكتروني غير صالح',
        'invalid_file_type' => 'نوع الملف غير مدعوم. يرجى استخدام JPG, PNG, or GIF',
        'file_too_large' => 'حجم الملف كبير جداً. الحد الأقصى هو 5MB',
        'error_creating_directory' => 'فشل في إنشاء مجلد الصور',
        'error_uploading_file' => 'فشل في رفع الصورة',
        'error_saving_data' => 'حدث خطأ أثناء حفظ البيانات',
        
        // Success Messages
        'company_updated' => 'تم تحديث بيانات الشركة: %s',
        'company_added' => 'تم إضافة شركة جديدة: %s\nكلمة المرور: %s',
        'company_update_success' => 'تم تحديث بيانات الشركة بنجاح',
        'company_add_success' => 'تم إضافة الشركة بنجاح. كلمة المرور هي: %s',
        
        // Orders
        'orders_list' => 'قائمة الطلبات',
        'order_number' => 'رقم الطلب',
        'order_type' => 'نوع الطلب',
        'order_date' => 'تاريخ الطلب',
        'delivery_date' => 'تاريخ التوصيل',
        'customer_name' => 'اسم العميل',
        'customer_phone' => 'رقم الهاتف',
        'total_cost' => 'التكلفة الإجمالية',
        'payment_status' => 'حالة الدفع',
        'order_status' => 'حالة الطلب',
        'driver_name' => 'اسم السائق',
        'driver_phone' => 'هاتف السائق',
        'assign_driver' => 'تعيين سائق',
        'update_status' => 'تحديث الحالة',
        'edit_order' => 'تعديل الطلب',
        'delete_order' => 'حذف الطلب',
        'view_details' => 'عرض التفاصيل',
        'print_invoice' => 'طباعة الفاتورة',
        'track_order' => 'تتبع الطلب',
        'not_assigned' => 'لم يتم التعيين',
        'all_statuses' => 'جميع الحالات',
        'search_orders' => 'البحث في الطلبات...',
        'no_orders' => 'لا توجد طلبات',
        'order_details' => 'تفاصيل الطلب',
        'company_info' => 'معلومات الشركة',
        'customer_info' => 'معلومات العميل',
        'driver_info' => 'معلومات السائق',
        'payment_info' => 'معلومات الدفع',
        'created_at' => 'تاريخ الإنشاء',
        'updated_at' => 'آخر تحديث',
        'contact_via_whatsapp' => 'تواصل عبر واتساب',
        'confirm_delete_order' => 'هل أنت متأكد من حذف الطلب؟',
        'paid' => 'مدفوع',
        'unpaid' => 'غير مدفوع',
        'currency_sar' => 'ريال',
        'invoice_title' => 'فاتورة طلب',
        'invoice_number' => 'رقم الفاتورة',
        
        // Order Status
        'status_pending' => 'قيد الانتظار',
        'status_accepted' => 'مقبول',
        'status_in_transit' => 'قيد التوصيل',
        'status_delivered' => 'تم التوصيل',
        'status_cancelled' => 'ملغي',
        'status_unknown' => 'غير معروف',
        
        // Order Status Updates
        'order_status_updated' => 'تم تحديث حالة الطلب رقم: %s',
        'order_deleted' => 'تم حذف الطلب رقم: %s',
        'close' => 'إغلاق',
        'order_info' => 'معلومات الطلب',
        'order_actions' => 'الإجراءات',
        'invoice_details' => 'تفاصيل الفاتورة',
        'print' => 'طباعة',
        'invoice_title' => 'فاتورة طلب',
        'invoice_number' => 'رقم الفاتورة: #%s',
        'order_date' => 'تاريخ الطلب',
        'order_status' => 'حالة الطلب',
        'payment_details' => 'تفاصيل الدفع',
        'total_amount' => 'المبلغ الإجمالي',
        'payment_method' => 'طريقة الدفع',
        'payment_date' => 'تاريخ الدفع',
        'transaction_id' => 'رقم العملية',
        'notes' => 'ملاحظات',

        // Revenue Management
        'revenue_analytics' => 'تحليلات الإيرادات',
        'filter_by_date' => 'تصفية حسب التاريخ',
        'start_date' => 'تاريخ البداية',
        'end_date' => 'تاريخ النهاية',
        'apply_filter' => 'تطبيق التصفية',
        'reset' => 'إعادة تعيين',
        'accounting_report' => 'التقرير المحاسبي',
        'total_amounts' => 'إجمالي المبالغ',
        'total_orders' => 'عدد الطلبات',
        'net_amounts' => 'صافي المبالغ (بدون التوصيل)',
        'company_dues' => 'المستحقات للشركات',
        'total_remaining' => 'إجمالي المبالغ المتبقية',
        'average_order_value' => 'متوسط قيمة الطلب',
        'delivery_fees' => 'رسوم التوصيل',
        'total_delivery_fees' => 'إجمالي رسوم التوصيل',
        'completed_orders' => 'الطلبات المكتملة',
        'average_delivery_fee' => 'متوسط رسوم التوصيل',
        'due_to_us' => 'مستحق لنا ✅',
        'due_on_us' => 'مستحق علينا ⚠️',
        'no_dues' => 'لا يوجد مستحقات✅',
        'company_accounts' => 'تفاصيل حسابات الشركات',
        'export_transactions' => 'تصدير العمليات',
        'delivery_fee' => 'رسوم التوصيل',
        'total_amount' => 'إجمالي المبلغ',
        'dues_after_fees' => 'المستحقات بعد خصم رسوم التوصيل',
        'paid_amount' => 'المبلغ المدفوع',
        'remaining' => 'المتبقي',
        'company_status' => 'حالة الشركة',
        'paid_by_company' => 'مدفوع من الشركة',
        'paid_to_company' => 'مدفوع منا إلى الشركة',
        'due_on_us_warning' => '⚠️ مستحق علينا',
        'due_to_us_info' => '💰 مستحق لنا',
        'register_payment' => 'تسجيل دفعة',
        'history' => 'السجل',
        'no_companies' => 'لا توجد شركات حالياً',
        'revenue_chart' => 'الإيرادات',
        'payment_methods_distribution' => 'توزيع طرق الدفع',

        // Payment Modal
        'payment_registration' => 'تسجيل دفعة',
        'payment_type' => 'نوع الدفعة',
        'select_payment_type' => 'اختر نوع الدفعة',
        'pay_to_company' => 'دفع للشركة',
        'receive_from_company' => 'استلام من الشركة',
        'amount' => 'المبلغ',
        'payment_method' => 'طريقة الدفع',
        'select_payment_method' => 'اختر طريقة الدفع',
        'cash' => 'نقدي',
        'bank_transfer' => 'تحويل بنكي',
        'check' => 'شيك',
        'reference_number' => 'رقم المرجع',
        'reference_hint' => 'رقم الشيك أو رقم التحويل البنكي',
        'notes' => 'ملاحظات',
        'cancel' => 'إلغاء',
        'register_payment' => 'تسجيل الدفعة',

        // Drivers Management
        'drivers_list' => 'قائمة السائقين',
        'driver_management' => 'إدارة السائقين',
        'add_new_driver' => 'إضافة سائق جديد',
        'edit_driver' => 'تعديل بيانات السائق',
        'driver_name' => 'اسم السائق',
        'driver_email' => 'البريد الإلكتروني',
        'driver_phone' => 'رقم الهاتف',
        'driver_age' => 'العمر',
        'driver_id_number' => 'رقم الهوية',
        'driver_license' => 'رقم رخصة القيادة',
        'vehicle_info' => 'معلومات المركبة',
        'vehicle_type' => 'نوع المركبة',
        'vehicle_model' => 'موديل المركبة',
        'plate_number' => 'لوحة المركبة',
        'driver_status' => 'حالة السائق',
        'driver_rating' => 'التقييم',
        'total_trips' => 'عدد الرحلات',
        'driver_earnings' => 'التحصيل من السائق',
        'driver_notes' => 'ملاحظات',
        'basic_info' => 'المعلومات الأساسية',
        'identity_info' => 'معلومات الهوية',
        'additional_info' => 'معلومات إضافية',
        'about_driver' => 'نبذة عن السائق',
        'driver_address' => 'العنوان',
        'current_status' => 'الحالة الحالية',
        'activate_account' => 'تفعيل الحساب',
        'driver_active' => 'السائق نشط',
        'save_data' => 'حفظ البيانات',
        'search_drivers' => 'البحث عن سائق...',
        'no_drivers' => 'لا يوجد سائقين مسجلين',
        'driver_details' => 'تفاصيل السائق',
        'contact_info' => 'معلومات الاتصال',
        'trip_statistics' => 'إحصائيات الرحلات',
        'completed_trips' => 'الرحلات المكتملة',
        'cancelled_trips' => 'الرحلات الملغاة',
        'current_orders' => 'الطلبات الحالية',
        'latest_activities' => 'أحدث الأنشطة',
        'driver_earnings_settings' => 'التحصيل من السواق',
        'earnings_amount' => 'مبلغ التحصيل ',
        'update_earnings' => 'تحديث التحصيل ',
        'driver_password' => 'كلمة المرور',
        'leave_empty_password' => 'اتركه فارغاً إذا كنت لا تريد تغيير كلمة المرور',
        'driver_profile' => 'الصورة الشخصية',
        'upload_profile' => 'تحميل صورة شخصية',
        'driver_updated' => 'تم تحديث بيانات السائق: %s',
        'driver_added' => 'تم إضافة سائق جديد: %s\nكلمة المرور: %s',
        'driver_update_success' => 'تم تحديث بيانات السائق بنجاح',
        'driver_add_success' => 'تم إضافة السائق بنجاح. كلمة المرور هي: %s',

        // Driver Details API
        'driver_id_required' => 'رقم السائق مطلوب',
        'driver_not_found' => 'لم يتم العثور على السائق',
        'database_error' => 'خطأ في قاعدة البيانات',
        'no_action' => 'بدون إجراء',
        'no_details' => 'لا توجد تفاصيل',
        'activity_type' => 'نوع النشاط',
        'activity_details' => 'تفاصيل النشاط',
        'activity_date' => 'تاريخ النشاط',

        // JavaScript Messages
        'copy_success' => 'تم نسخ بيانات السائق بنجاح',
        'copy_error' => 'فشل في نسخ البيانات',
        'whatsapp_message' => 'مرحباً، أود التواصل معك بخصوص الخدمة',
        'server_connection_error' => 'فشل الاتصال بالخادم',
        'data_fetch_error' => 'فشل في جلب البيانات',
        'back' => 'رجوع',

        // Complaints Management
        'no_complaints' => 'لا توجد شكاوى حالياً',
        'complaint_number' => 'رقم الشكوى',
        'complaint_company' => 'الشركة',
        'complaint_driver' => 'السائق',
        'complaint_request' => 'رقم الطلب',
        'complaint_subject' => 'موضوع الشكوى',
        'complaint_details' => 'تفاصيل الشكوى',
        'complaint_priority' => 'الأولوية',
        'complaint_status' => 'الحالة',
        'complaint_date' => 'تاريخ الشكوى',
        'latest_response' => 'آخر رد',
        'response_count' => 'عدد الردود',
        'response_by' => 'رد من',
        'view_details' => 'عرض التفاصيل',
        'priority_high' => 'عالية',
        'priority_medium' => 'متوسطة',
        'priority_low' => 'منخفضة',
        'status_new' => 'جديدة',
        'status_in_progress' => 'قيد المعالجة',
        'status_resolved' => 'تم الحل',
        'status_closed' => 'مغلقة',
        'management' => 'الإدارة',
        'responses' => 'الردود',
        'add_response' => 'إضافة رد',
        'write_response' => 'اكتب ردك هنا...',
        'submit_response' => 'إرسال الرد',
        'response_success' => 'تم إرسال الرد بنجاح',
        'response_error' => 'حدث خطأ أثناء إرسال الرد',

        // Complaint Details
        'company_driver_info' => 'معلومات الشركة والسائق',
        'delivery_info' => 'معلومات التوصيل',
        'pickup_location' => 'موقع الاستلام',
        'delivery_location' => 'موقع التسليم',
        'responses_followup' => 'الردود والمتابعة',
        'no_responses' => 'لا توجد ردود حتى الآن',
        'company_response' => 'رد الشركة',
        'admin_response' => 'رد الإدارة',

        // Feedback Page
        'customer_feedback' => 'ملاحظات العملاء',
        'feedback_order_number' => 'رقم الطلب',
        'feedback_customer' => 'العميل',
        'feedback_phone' => 'رقم الهاتف',
        'feedback_driver' => 'السائق',
        'feedback_from' => 'من',
        'feedback_to' => 'إلى',
        'feedback_notes' => 'الملاحظات',
        'feedback_date' => 'تاريخ الملاحظة',
        'feedback_order_status' => 'حالة الطلب',
        'view_feedback' => 'عرض الملاحظات',
        'no_driver_assigned' => 'لم يتم تعيين سائق',
        'feedback_modal_title' => 'ملاحظات الطلب رقم',
        'close' => 'إغلاق',

        // Reports Page
        'reports_dashboard' => 'لوحة التقارير',
        'orders_report' => 'تقرير الطلبات',
        'orders_report_desc' => 'عرض إحصائيات واتجاهات الطلبات التفصيلية',
        'drivers_report' => 'تقرير السائقين',
        'drivers_report_desc' => 'تحليل أداء السائقين والتوصيلات',
        'revenue_report' => 'تقرير الإيرادات',
        'revenue_report_desc' => 'تتبع الإيرادات والمؤشرات المالية',
        'complaints_report' => 'تقرير الشكاوى',
        'complaints_report_desc' => 'مراقبة شكاوى العملاء وحلولها',
        'employees_report' => 'تقرير الموظفين',
        'employees_report_desc' => 'مراجعة أداء وإحصائيات الموظفين',
        'payments_report' => 'تقرير المدفوعات',
        'payments_report_desc' => 'عرض سجل المدفوعات والمعاملات',
        'view_report' => 'عرض التقرير',

        // Employees Management
        'employees_management' => 'إدارة الموظفين',
        'add_new_employee' => 'إضافة موظف جديد',
        'employee_list' => 'قائمة الموظفين',
        'employee_info' => 'معلومات الموظف',
        'username' => 'اسم المستخدم',
        'password' => 'كلمة المرور',
        'full_name' => 'الاسم الكامل',
        'email' => 'البريد الإلكتروني',
        'phone' => 'رقم الهاتف',
        'department' => 'القسم',
        'role' => 'الدور الوظيفي',
        'management_dept' => 'إدارة',
        'accounting_dept' => 'محاسبة',
        'drivers_supervisor_dept' => 'مشرف السواقين',
        'general_manager' => 'مدير عام',
        'system_admin' => 'مدير النظام',
        'employee' => 'موظف',
        'select_department' => 'اختر القسم',
        'select_role' => 'اختر الدور',
        'confirm_delete_employee' => 'هل أنت متأكد من حذف هذا الموظف؟',
        'cannot_delete_gm' => 'لا يمكن حذف المدير العام',
        'employee_added' => 'تم إضافة الموظف بنجاح',
        'employee_deleted' => 'تم حذف الموظف بنجاح',
        'error_adding_employee' => 'حدث خطأ أثناء إضافة الموظف',
        'error_deleting_employee' => 'حدث خطأ أثناء حذف الموظف',
        'total_employees' => 'إجمالي الموظفين',
        'active_employees' => 'الموظفين النشطين',
        'inactive_employees' => 'الموظفين غير النشطين',
        'no_employees' => 'لا يوجد موظفين حالياً',
        'contact_info' => 'معلومات الاتصال',
        'quick_stats' => 'إحصائيات سريعة',
        'confirm_delete' => 'تأكيد الحذف',
        'delete_warning' => 'لا يمكن التراجع عن هذا الإجراء',

        // Edit Employee Page
        'edit_employee' => 'تعديل بيانات الموظف',
        'new_password' => 'كلمة المرور الجديدة',
        'leave_empty_password' => 'اتركها فارغة إذا لم ترد تغييرها',
        'employee_not_found' => 'الموظف غير موجود',
        'no_permission_edit' => 'ليس لديك صلاحية تعديل بيانات هذا الموظف',
        'cannot_edit_gm' => 'لا يمكن تعديل بيانات المدير العام',
        'cannot_edit_admin' => 'لا يمكن تعديل بيانات مدير النظام',
        'duplicate_username_email' => 'اسم المستخدم أو البريد الإلكتروني مستخدم بالفعل',
        'employee_updated' => 'تم تحديث بيانات الموظف بنجاح',
        'error_updating_employee' => 'حدث خطأ أثناء تحديث البيانات',

        // Profile Page
        'current_password' => 'كلمة المرور الحالية',
        'save_changes' => 'حفظ التغييرات',
        'error_fetching_data' => 'حدث خطأ في جلب البيانات',
        'error_updating_data' => 'حدث خطأ في تحديث البيانات',
        'data_updated_successfully' => 'تم تحديث البيانات بنجاح',
        'incorrect_current_password' => 'كلمة المرور الحالية غير صحيحة',

        // New translations
        'active_companies' => 'الشركات النشطة',
        'active_drivers' => 'السائقين النشطين',
        'monthly_orders' => 'طلبات الشهر',
        'new_complaints' => 'شكوى جديدة',
        'monthly_orders_analysis' => 'تحليل الطلبات الشهرية',
        'orders_status_distribution' => 'توزيع حالات الطلبات',
        'average_order_value' => 'متوسط قيمة الطلب',
        'total_revenue' => 'إجمالي الإيرادات',
        'orders_completion_rate' => 'معدل إكمال الطلبات',
        'customer_satisfaction' => 'رضا العملاء',

        // Chart translations
        'total_orders' => 'إجمالي الطلبات',
        'completed_orders' => 'الطلبات المكتملة',
        'growth' => 'النمو',
        '6_months' => '6 أشهر',
        '1_year' => 'سنة',
        'sar' => 'ر.س',
        'orders' => 'طلبات',

        // Dashboard Charts
        'drivers_performance' => 'أداء السائقين',
        'orders_growth_rate' => 'معدل نمو الطلبات',
        'hourly_orders_distribution' => 'توزيع الطلبات حسب الساعة',
        'top_performing_drivers' => 'أفضل السائقين أداءً',
        'completion_rate' => 'معدل الإكمال',
        'rating' => 'التقييم',
        'average_delivery_time' => 'متوسط وقت التوصيل',
        'minutes' => 'دقيقة',
        'hour' => 'الساعة',
        'orders_count' => 'عدد الطلبات',
        'sales_amount' => 'قيمة المبيعات',
        'growth_rate' => 'معدل النمو',
    ],
    'en' => [
        // General
        'dashboard' => 'Dashboard',
        'orders' => 'Orders',
        'companies' => 'Companies',
        'drivers' => 'Drivers',
        'complaints' => 'Complaints',
        'feedback' => 'Customer Feedback',
        'reports' => 'Reports',
        'revenue' => 'Revenue',
        'driver_earnings' => 'Driver Earnings',
        'employees' => 'Employees',
        'profile' => 'Profile',
        'logout' => 'Logout',
        'notifications' => 'Notifications',
        'admin_panel' => 'Admin Panel',
        
        // Status
        'status_active' => 'Active',
        'status_inactive' => 'Inactive',
        'status_pending' => 'Pending',
        'status_accepted' => 'Accepted',
        'status_in_transit' => 'In Transit',
        'status_delivered' => 'Delivered',
        'status_cancelled' => 'Cancelled',
        'status_unknown' => 'Unknown',
        
        // Driver Status
        'driver_available' => 'Available',
        'driver_busy' => 'Busy',
        'driver_offline' => 'Offline',
        
        // Actions
        'whatsapp' => 'Contact via WhatsApp',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'activate' => 'Activate',
        'deactivate' => 'Deactivate',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'search' => 'Search',
        'add_new' => 'Add New',
        'view' => 'View',
        'export' => 'Export',
        'print' => 'Print',
        
        // System
        'system_title' => 'Transport Management System',
        'loading' => 'Loading...',
        'no_data' => 'No data available',
        'error' => 'Error',
        'success' => 'Success',
        'warning' => 'Warning',
        'info' => 'Information',
        'orders_management' => 'Orders Management',
        'companies_management' => 'Companies Management',
        'drivers_management' => 'Drivers Management',
        'complaints_management' => 'Complaints Management',
        'feedback_management' => 'Feedback Management',
        'reports_management' => 'Reports Management',
        'revenue_management' => 'Revenue Management',
        'driver_earnings_settings' => 'Earned from drivers',
        'employees_management' => 'Employees Management',
        
        // Companies
        'company_name' => 'Company Name',
        'company_email' => 'Email',
        'company_phone' => 'Phone',
        'company_address' => 'Address',
        'company_logo' => 'Company Logo',
        'company_contact' => 'Contact Person',
        'total_orders' => 'Total Orders',
        'registration_date' => 'Registration Date',
        
        // Confirmations
        'confirm_delete' => 'Are you sure you want to delete this item?',
        'confirm_activate' => 'Are you sure you want to activate this item?',
        'confirm_deactivate' => 'Are you sure you want to deactivate this item?',
        
        // Navigation
        'previous' => 'Previous',
        'next' => 'Next',
        'page_navigation' => 'Page Navigation',
        
        // Messages
        'no_results' => 'No results found',
        'success_message' => 'Operation completed successfully',
        'error_message' => 'An error occurred',
        'required_field' => 'This field is required',
        
        // Common
        'date' => 'Date',
        'time' => 'Time',
        'status' => 'Status',
        'actions' => 'Actions',
        'details' => 'Details',
        'notes' => 'Notes',
        'description' => 'Description',
        'type' => 'Type',
        'category' => 'Category',
        'price' => 'Price',
        'quantity' => 'Quantity',
        'total' => 'Total',
        
        // Company Form
        'edit_company' => 'Edit Company',
        'add_company' => 'Add Company',
        'add_new_company' => 'Add New Company',
        'upload_company_logo' => 'Upload Company Logo',
        'commercial_record' => 'Commercial Record',
        'tax_number' => 'Tax Number',
        'contact_person' => 'Contact Person',
        'contact_phone' => 'Contact Phone',
        'activate_company' => 'Activate Company',
        
        // Form Validation
        'invalid_email' => 'Invalid email address',
        'invalid_file_type' => 'Invalid file type. Please use JPG, PNG, or GIF',
        'file_too_large' => 'File is too large. Maximum size is 5MB',
        'error_creating_directory' => 'Failed to create image directory',
        'error_uploading_file' => 'Failed to upload image',
        'error_saving_data' => 'Error saving data',
        
        // Success Messages
        'company_updated' => 'Company updated: %s',
        'company_added' => 'New company added: %s\nPassword: %s',
        'company_update_success' => 'Company updated successfully',
        'company_add_success' => 'Company added successfully. Password is: %s',
        
        // Orders
        'orders_list' => 'Orders List',
        'order_number' => 'Order Number',
        'order_type' => 'Order Type',
        'order_date' => 'Order Date',
        'delivery_date' => 'Delivery Date',
        'customer_name' => 'Customer Name',
        'customer_phone' => 'Phone Number',
        'total_cost' => 'Total Cost',
        'payment_status' => 'Payment Status',
        'order_status' => 'Order Status',
        'driver_name' => 'Driver Name',
        'driver_phone' => 'Driver Phone',
        'assign_driver' => 'Assign Driver',
        'update_status' => 'Update Status',
        'edit_order' => 'Edit Order',
        'delete_order' => 'Delete Order',
        'view_details' => 'View Details',
        'print_invoice' => 'Print Invoice',
        'track_order' => 'Track Order',
        'not_assigned' => 'Not Assigned',
        'all_statuses' => 'All Statuses',
        'search_orders' => 'Search orders...',
        'no_orders' => 'No orders found',
        'order_details' => 'Order Details',
        'company_info' => 'Company Information',
        'customer_info' => 'Customer Information',
        'driver_info' => 'Driver Information',
        'payment_info' => 'Payment Information',
        'created_at' => 'Created At',
        'updated_at' => 'Last Updated',
        'contact_via_whatsapp' => 'Contact via WhatsApp',
        'confirm_delete_order' => 'Are you sure you want to delete this order?',
        'paid' => 'Paid',
        'unpaid' => 'Unpaid',
        'currency_sar' => 'SAR',
        'invoice_title' => 'Order Invoice',
        'invoice_number' => 'Invoice Number',
        
        // Order Status
        'status_pending' => 'Pending',
        'status_accepted' => 'Accepted',
        'status_in_transit' => 'In Transit',
        'status_delivered' => 'Delivered',
        'status_cancelled' => 'Cancelled',
        'status_unknown' => 'Unknown',
        
        // Order Status Updates
        'order_status_updated' => 'Order status updated for order #%s',
        'order_deleted' => 'Order #%s has been deleted',
        'close' => 'Close',
        'order_info' => 'Order Information',
        'order_actions' => 'Actions',
        'invoice_details' => 'Invoice Details',
        'print' => 'Print',
        'invoice_title' => 'فاتورة طلب',
        'invoice_number' => 'رقم الفاتورة: #%s',
        'order_date' => 'تاريخ الطلب',
        'order_status' => 'حالة الطلب',
        'payment_details' => 'تفاصيل الدفع',
        'total_amount' => 'المبلغ الإجمالي',
        'payment_method' => 'طريقة الدفع',
        'payment_date' => 'تاريخ الدفع',
        'transaction_id' => 'رقم العملية',
        'notes' => 'ملاحظات',

        // Revenue Management
        'revenue_analytics' => 'Revenue Analytics',
        'filter_by_date' => 'Filter by Date',
        'start_date' => 'Start Date',
        'end_date' => 'End Date',
        'apply_filter' => 'Apply Filter',
        'reset' => 'Reset',
        'accounting_report' => 'Accounting Report',
        'total_amounts' => 'Total Amounts',
        'total_orders' => 'Total Orders',
        'net_amounts' => 'Net Amounts (Excluding Delivery)',
        'company_dues' => 'Company Dues',
        'total_remaining' => 'Total Remaining Amount',
        'average_order_value' => 'Average Order Value',
        'delivery_fees' => 'Delivery Fees',
        'total_delivery_fees' => 'Total Delivery Fees',
        'completed_orders' => 'Completed Orders',
        'average_delivery_fee' => 'Average Delivery Fee',
        'due_to_us' => 'Due to Us ✅',
        'due_on_us' => 'Due on Us ⚠️',
        'no_dues' => 'No Dues ✅',
        'company_accounts' => 'Company Accounts Details',
        'export_transactions' => 'Export Transactions',
        'delivery_fee' => 'Delivery Fee',
        'total_amount' => 'Total Amount',
        'dues_after_fees' => 'Dues After Delivery Fees',
        'paid_amount' => 'Paid Amount',
        'remaining' => 'Remaining',
        'company_status' => 'Company Status',
        'paid_by_company' => 'Paid by Company',
        'paid_to_company' => 'Paid to Company',
        'due_on_us_warning' => '⚠️ Due on Us',
        'due_to_us_info' => '💰 Due to Us',
        'register_payment' => 'Register Payment',
        'history' => 'History',
        'no_companies' => 'No companies available',
        'revenue_chart' => 'Revenue',
        'payment_methods_distribution' => 'Payment Methods Distribution',

        // Payment Modal
        'payment_registration' => 'Payment Registration',
        'payment_type' => 'Payment Type',
        'select_payment_type' => 'Select Payment Type',
        'pay_to_company' => 'Pay to Company',
        'receive_from_company' => 'Receive from Company',
        'amount' => 'Amount',
        'payment_method' => 'Payment Method',
        'select_payment_method' => 'Select Payment Method',
        'cash' => 'Cash',
        'bank_transfer' => 'Bank Transfer',
        'check' => 'Check',
        'reference_number' => 'Reference Number',
        'reference_hint' => 'Check number or bank transfer number',
        'notes' => 'Notes',
        'cancel' => 'Cancel',
        'register_payment' => 'Register Payment',

        // Drivers Management
        'drivers_list' => 'Drivers List',
        'driver_management' => 'Driver Management',
        'add_new_driver' => 'Add New Driver',
        'edit_driver' => 'Edit Driver',
        'driver_name' => 'Driver Name',
        'driver_email' => 'Email',
        'driver_phone' => 'Phone Number',
        'driver_age' => 'Age',
        'driver_id_number' => 'ID Number',
        'driver_license' => 'License Number',
        'vehicle_info' => 'Vehicle Information',
        'vehicle_type' => 'Vehicle Type',
        'vehicle_model' => 'Vehicle Model',
        'plate_number' => 'Plate Number',
        'driver_status' => 'Driver Status',
        'driver_rating' => 'Rating',
        'total_trips' => 'Total Trips',
        'driver_earnings' => 'Earned from drivers',
        'driver_notes' => 'Notes',
        'basic_info' => 'Basic Information',
        'identity_info' => 'Identity Information',
        'additional_info' => 'Additional Information',
        'about_driver' => 'About Driver',
        'driver_address' => 'Address',
        'current_status' => 'Current Status',
        'activate_account' => 'Activate Account',
        'driver_active' => 'Driver Active',
        'save_data' => 'Save Data',
        'search_drivers' => 'Search drivers...',
        'no_drivers' => 'No drivers found',
        'driver_details' => 'Driver Details',
        'contact_info' => 'Contact Information',
        'trip_statistics' => 'Trip Statistics',
        'completed_trips' => 'Completed Trips',
        'cancelled_trips' => 'Cancelled Trips',
        'current_orders' => 'Current Orders',
        'latest_activities' => 'Latest Activities',
        'driver_earnings_management' => 'Earned from drivers',
        'earnings_amount' => 'Earnings Amount',
        'update_earnings' => 'Update Earnings',
        'driver_password' => 'Password',
        'leave_empty_password' => 'Leave empty if you don\'t want to change the password',
        'driver_profile' => 'Profile Picture',
        'upload_profile' => 'Upload Profile Picture',
        'driver_updated' => 'Driver updated: %s',
        'driver_added' => 'New driver added: %s\nPassword: %s',
        'driver_update_success' => 'Driver updated successfully',
        'driver_add_success' => 'Driver added successfully. Password is: %s',

        // Driver Details API
        'driver_id_required' => 'Driver ID is required',
        'driver_not_found' => 'Driver not found',
        'database_error' => 'Database error',
        'no_action' => 'No action',
        'no_details' => 'No details available',
        'activity_type' => 'Activity Type',
        'activity_details' => 'Activity Details',
        'activity_date' => 'Activity Date',

        // JavaScript Messages
        'copy_success' => 'Driver information copied successfully',
        'copy_error' => 'Failed to copy data',
        'whatsapp_message' => 'Hello, I would like to contact you regarding the service',
        'server_connection_error' => 'Server connection failed',
        'data_fetch_error' => 'Failed to fetch data',
        'back' => 'Back',

        // Complaints Management
        'complaints_management' => 'Complaints Management',
        'no_complaints' => 'No complaints available',
        'complaint_number' => 'Complaint Number',
        'complaint_company' => 'Company',
        'complaint_driver' => 'Driver',
        'complaint_request' => 'Request Number',
        'complaint_subject' => 'Subject',
        'complaint_details' => 'Complaint Details',
        'complaint_priority' => 'Priority',
        'complaint_status' => 'Status',
        'complaint_date' => 'Date',
        'latest_response' => 'Latest Response',
        'response_count' => 'Responses',
        'response_by' => 'Response by',
        'view_details' => 'View Details',
        'priority_high' => 'High',
        'priority_medium' => 'Medium',
        'priority_low' => 'Low',
        'status_new' => 'New',
        'status_in_progress' => 'In Progress',
        'status_resolved' => 'Resolved',
        'status_closed' => 'Closed',
        'management' => 'Management',
        'responses' => 'Responses',
        'add_response' => 'Add Response',
        'write_response' => 'Write your response here...',
        'submit_response' => 'Submit Response',
        'response_success' => 'Response submitted successfully',
        'response_error' => 'Error submitting response',
        'loading' => 'Loading...',

        // Complaint Details
        'company_driver_info' => 'Company & Driver Information',
        'delivery_info' => 'Delivery Information',
        'pickup_location' => 'Pickup Location',
        'delivery_location' => 'Delivery Location',
        'responses_followup' => 'Responses & Follow-up',
        'no_responses' => 'No responses yet',
        'company_response' => 'Company Response',
        'admin_response' => 'Management Response',

        // Feedback Page
        'customer_feedback' => 'Customer Feedback',
        'feedback_order_number' => 'Order Number',
        'feedback_customer' => 'Customer',
        'feedback_phone' => 'Phone Number',
        'feedback_driver' => 'Driver',
        'feedback_from' => 'From',
        'feedback_to' => 'To',
        'feedback_notes' => 'Notes',
        'feedback_date' => 'Feedback Date',
        'feedback_order_status' => 'Order Status',
        'view_feedback' => 'View Feedback',
        'no_driver_assigned' => 'No driver assigned',
        'feedback_modal_title' => 'Feedback for Order #',
        'close' => 'Close',

        // Reports Page
        'reports_dashboard' => 'Reports Dashboard',
        'orders_report' => 'Orders Report',
        'orders_report_desc' => 'View detailed order statistics and trends',
        'drivers_report' => 'Drivers Report',
        'drivers_report_desc' => 'Analyze driver performance and deliveries',
        'revenue_report' => 'Revenue Report',
        'revenue_report_desc' => 'Track revenue and financial indicators',
        'complaints_report' => 'Complaints Report',
        'complaints_report_desc' => 'Monitor customer complaints and resolutions',
        'employees_report' => 'Employees Report',
        'employees_report_desc' => 'Review employee performance and statistics',
        'payments_report' => 'Payments Report',
        'payments_report_desc' => 'View payment history and transactions',
        'view_report' => 'View Report',

        // Employees Management
        'employees_management' => 'Employees Management',
        'add_new_employee' => 'Add New Employee',
        'employee_list' => 'Employees List',
        'employee_info' => 'Employee Information',
        'username' => 'Username',
        'password' => 'Password',
        'full_name' => 'Full Name',
        'email' => 'Email',
        'phone' => 'Phone Number',
        'department' => 'Department',
        'role' => 'Role',
        'management_dept' => 'Management',
        'accounting_dept' => 'Accounting',
        'drivers_supervisor_dept' => 'Drivers Supervisor',
        'general_manager' => 'General Manager',
        'system_admin' => 'System Admin',
        'employee' => 'Employee',
        'select_department' => 'Select Department',
        'select_role' => 'Select Role',
        'confirm_delete_employee' => 'Are you sure you want to delete this employee?',
        'cannot_delete_gm' => 'Cannot delete General Manager',
        'employee_added' => 'Employee added successfully',
        'employee_deleted' => 'Employee deleted successfully',
        'error_adding_employee' => 'Error occurred while adding employee',
        'error_deleting_employee' => 'Error occurred while deleting employee',
        'total_employees' => 'Total Employees',
        'active_employees' => 'Active Employees',
        'inactive_employees' => 'Inactive Employees',
        'no_employees' => 'No employees available',
        'contact_info' => 'Contact Information',
        'quick_stats' => 'Quick Statistics',
        'confirm_delete' => 'Confirm Delete',
        'delete_warning' => 'This action cannot be undone',

        // Edit Employee Page
        'edit_employee' => 'Edit Employee',
        'new_password' => 'New Password',
        'leave_empty_password' => 'Leave empty if you don\'t want to change it',
        'employee_not_found' => 'Employee not found',
        'no_permission_edit' => 'You don\'t have permission to edit this employee',
        'cannot_edit_gm' => 'Cannot edit General Manager data',
        'cannot_edit_admin' => 'Cannot edit System Admin data',
        'duplicate_username_email' => 'Username or email is already in use',
        'employee_updated' => 'Employee data updated successfully',
        'error_updating_employee' => 'Error occurred while updating data',

        // Profile Page
        'current_password' => 'Current Password',
        'save_changes' => 'Save Changes',
        'error_fetching_data' => 'Error occurred while fetching data',
        'error_updating_data' => 'Error occurred while updating data',
        'data_updated_successfully' => 'Data updated successfully',
        'incorrect_current_password' => 'Current password is incorrect',

        // New translations
        'active_companies' => 'Active Companies',
        'active_drivers' => 'Active Drivers',
        'monthly_orders' => 'Monthly Orders',
        'new_complaints' => 'New Complaints',
        'monthly_orders_analysis' => 'Monthly Orders Analysis',
        'orders_status_distribution' => 'Orders Status Distribution',
        'average_order_value' => 'Average Order Value',
        'total_revenue' => 'Total Revenue',
        'orders_completion_rate' => 'Orders Completion Rate',
        'customer_satisfaction' => 'Customer Satisfaction',

        // Chart translations
        'total_orders' => 'Total Orders',
        'completed_orders' => 'Completed Orders',
        'growth' => 'Growth',
        '6_months' => '6 Months',
        '1_year' => '1 Year',
        'sar' => 'SAR',
        'orders' => 'orders',

        // Dashboard Charts
        'drivers_performance' => 'Drivers Performance',
        'orders_growth_rate' => 'Orders Growth Rate',
        'hourly_orders_distribution' => 'Hourly Orders Distribution',
        'top_performing_drivers' => 'Top Performing Drivers',
        'completion_rate' => 'Completion Rate',
        'rating' => 'Rating',
        'average_delivery_time' => 'Average Delivery Time',
        'minutes' => 'minutes',
        'hour' => 'Hour',
        'orders_count' => 'Orders Count',
        'sales_amount' => 'Sales Amount',
        'growth_rate' => 'Growth Rate',
    ]
];

// Translation function
function __($key) {
    global $translations;
    $lang = $_SESSION['lang'] ?? 'ar'; // Default to Arabic if no language is set
    return $translations[$lang][$key] ?? $key;
} 